### PR TITLE
Forbid incompatible ansible-core versions >= 2.13

### LINKED ISSUE #113: [Bug report] ansible-playbook-grapher doesnt work with ansible-core 2.13.1
**Describe the bug**

When running `ansible-playbook-grapher` (without arguments), I get the exception
```
Traceback (most recent call last):
  File "/tmp/tmp.weiU6YpNir/virtualenv/bin/ansible-playbook-grapher", line 33, in <module>
    sys.exit(load_entry_point('ansible-playbook-grapher==1.1.1', 'console_scripts', 'ansible-playbook-grapher')())
  File "/tmp/tmp.weiU6YpNir/virtualenv/lib/python3.9/site-packages/ansibleplaybookgrapher/cli.py", line 249, in main
    cli.run()
  File "/tmp/tmp.weiU6YpNir/virtualenv/lib/python3.9/site-packages/ansibleplaybookgrapher/cli.py", line 52, in run
    super().run()
  File "/tmp/tmp.weiU6YpNir/virtualenv/lib/python3.9/site-packages/ansible/cli/__init__.py", line 109, in run
    self.parse()
  File "/tmp/tmp.weiU6YpNir/virtualenv/lib/python3.9/site-packages/ansible/cli/__init__.py", line 405, in parse
    self.init_parser()
  File "/tmp/tmp.weiU6YpNir/virtualenv/lib/python3.9/site-packages/ansibleplaybookgrapher/cli.py", line 188, in init_parser
    super().init_parser(
  File "/tmp/tmp.weiU6YpNir/virtualenv/lib/python3.9/site-packages/ansible/cli/__init__.py", line 336, in init_parser
    self.parser = opt_help.create_base_parser(self.name, usage=usage, desc=desc, epilog=epilog)
AttributeError: 'PlaybookGrapherCLI' object has no attribute 'name'
```

**To Reproduce**
```
workdir="$(mktemp -d)"
echo "Working in $workdir, you have to clean this up manually"

cd "$workdir"
python -m venv virtualenv
source virtualenv/bin/activate
git clone 'https://github.com/haidaraM/ansible-playbook-grapher'
cd ansible-playbook-grapher
pip install -r requirements.txt
pip install .

ansible-playbook-grapher

```
**Versions:**
Outputs of :
 - `ansible --version`
```
ansible [core 2.13.1]
  config file = None
  configured module search path = ['/home/jan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /tmp/tmp.weiU6YpNir/virtualenv/lib/python3.9/site-packages/ansible
  ansible collection location = /home/jan/.ansible/collections:/usr/share/ansible/collections
  executable location = /tmp/tmp.weiU6YpNir/virtualenv/bin/ansible
  python version = 3.9.13 (main, May 17 2022, 14:19:07) [GCC 11.3.0]
  jinja version = 3.1.2
  libyaml = True
```

 - `ansible-playbook-grapher --version`
Doesn't work, leads to above exception

### PR DESCRIPTION
**Pull request by jheidbrink**
Fixes #113 by further constraining the ansible-core version. On the long run ansible-playbook-grapher should probably be made compatible with that version.

### CODE REVIEW

**Comment by mohamed-haidara-cko** [comment]
Thanks for the contribution. Released in 1.1.2
